# Generated by Django 4.2 on 2025-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprosweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
